### ISSUE TITLE
Guard startup fails

### ISSUE THREAD

**Issue by geewiz** [Sixeight/guard-notifier-blink1#2]
After following the setup instructions, I get the following error when I start Guard:

```
ERROR - Invalid Guardfile, original error is:
> [#]
> [#] Notifier is not a module,
> [#] backtrace:
> [#]   (dsl)> $GEM_PATH[0]/gems/guard-notifier-blink1-0.2.2/lib/guard/notifier/blink1.rb:3:in `<module:Guard>'
> [#]   (dsl)> $GEM_PATH[0]/gems/guard-notifier-blink1-0.2.2/lib/guard/notifier/blink1.rb:2:in `<top (required)>'
> [#]   (dsl)> ./Guardfile:63:in `require'
> [#]   (dsl)> ./Guardfile:63:in `evaluate'
> [#]   (dsl)> $GEM_PATH[0]/gems/guard-2.13.0/lib/guard/dsl.rb:377:in `instance_eval'
> [#]   (dsl)> $GEM_PATH[0]/gems/guard-2.13.0/lib/guard/dsl.rb:377:in `evaluate'
> [#]   (dsl)> $GEM_PATH[0]/gems/guard-2.13.0/lib/guard/guardfile/evaluator.rb:91:in `evaluate'
> [#]   (dsl)> $GEM_PATH[0]/gems/guard-2.13.0/lib/guard.rb:134:in `_evaluate'
> [#]   (dsl)> $GEM_PATH[0]/gems/guard-2.13.0/lib/guard.rb:49:in `setup'
> [#]   (dsl)> $GEM_PATH[0]/gems/guard-2.13.0/lib/guard/commander.rb:32:in `start'
> [#]   (dsl)> $GEM_PATH[0]/gems/guard-2.13.0/lib/guard/cli/environments/valid.rb:16:in `start_guard'
> [#]   (dsl)> $GEM_PATH[0]/gems/guard-2.13.0/lib/guard/cli.rb:122:in `start'
> [#]   (dsl)> $GEM_PATH[0]/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
> [#]   (dsl)> $GEM_PATH[0]/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
> [#]   (dsl)> $GEM_PATH[0]/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
> [#]   (dsl)> $GEM_PATH[0]/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
> [#]   (dsl)> $GEM_PATH[0]/gems/guard-2.13.0/lib/guard/aruba_adapter.rb:32:in `execute'
> [#]   (dsl)> $GEM_PATH[0]/gems/guard-2.13.0/lib/guard/aruba_adapter.rb:19:in `execute!'
> [#]   (dsl)> $GEM_PATH[0]/gems/guard-2.13.0/bin/_guard-core:11:in `<main>'
```

**Comment by jamesbebbington** [comment]
Yup, just bought a blink(1), installed `blink1-tool` and followed setup instructions, same error:

```
$ guard
01:00:00 - ERROR - Invalid Guardfile, original error is: 
> [#] 
> [#] Notifier is not a module, 
> [#] backtrace: 
> [#] 	(dsl)> $GEM_PATH[0]/gems/guard-notifier-blink1-0.2.2/lib/guard/notifier/blink1.rb:3:in `<module:Guard>'
> [#] 	(dsl)> $GEM_PATH[0]/gems/guard-notifier-blink1-0.2.2/lib/guard/notifier/blink1.rb:2:in `<top (required)>'
> [#] 	(dsl)> ./Guardfile:20:in `require'
> [#] 	(dsl)> ./Guardfile:20:in `evaluate'
> [#] 	(dsl)> $GEM_PATH[0]/gems/guard-2.14.2/lib/guard/dsl.rb:377:in `instance_eval'
> [#] 	(dsl)> $GEM_PATH[0]/gems/guard-2.14.2/lib/guard/dsl.rb:377:in `evaluate'
> [#] 	(dsl)> $GEM_PATH[0]/gems/guard-2.14.2/lib/guard/guardfile/evaluator.rb:89:in `evaluate'
> [#] 	(dsl)> $GEM_PATH[0]/gems/guard-2.14.2/lib/guard.rb:134:in `_evaluate'
> [#] 	(dsl)> $GEM_PATH[0]/gems/guard-2.14.2/lib/guard.rb:49:in `setup'
> [#] 	(dsl)> $GEM_PATH[0]/gems/guard-2.14.2/lib/guard/commander.rb:32:in `start'
> [#] 	(dsl)> $GEM_PATH[0]/gems/guard-2.14.2/lib/guard/cli/environments/valid.rb:16:in `start_guard'
> [#] 	(dsl)> $GEM_PATH[0]/gems/guard-2.14.2/lib/guard/cli.rb:122:in `start'
> [#] 	(dsl)> $GEM_PATH[0]/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
> [#] 	(dsl)> $GEM_PATH[0]/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
> [#] 	(dsl)> $GEM_PATH[0]/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
> [#] 	(dsl)> $GEM_PATH[0]/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
> [#] 	(dsl)> $GEM_PATH[0]/gems/guard-2.14.2/lib/guard/aruba_adapter.rb:32:in `execute'
> [#] 	(dsl)> $GEM_PATH[0]/gems/guard-2.14.2/lib/guard/aruba_adapter.rb:19:in `execute!'
> [#] 	(dsl)> $GEM_PATH[0]/gems/guard-2.14.2/bin/_guard-core:11:in `<main>'

$ blink1-tool --version
blink1-tool version: v2.0.1-macosx-x86_64, fw version: 205

$ guard --version
Guard version 2.14.2
```
